apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-web-page
  labels:
    app: store-web-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store-web-page
  template:
    metadata:
      labels:
        app:  store-web-page
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: store-web-page
        image: dhanavandhan/store-web-page:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000